### ISSUE TITLE
Support to FBSDKCoreKit (~> 17.0)

### ISSUE THREAD

**Issue by lcsvcn** [Innim/flutter_login_facebook#109]
<img width="867" alt="Screenshot 2024-04-16 at 08 54 44" src="https://github.com/Innim/flutter_login_facebook/assets/6011385/b9704165-c773-41b2-b2d6-4ac4cadd25a9">

**Comment by lcsvcn** [comment]
https://github.com/Innim/flutter_login_facebook/pull/102

**Comment by greymag** [comment]
Hello. Unfortunately, for version 17.0 it is not that simple. Starting with this version, Facebook changes the behavior depending on whether AdvertiserTracking permission has been granted or not.

See #108 for details.

I will implement support for this version shortly, but you are still need to implement support of this behavior on your side.

Meanwhile you still can use previous version of FB SDK (16.2.1), it works perfectly fine (better than new one IMHO).

**Comment by nicolobozzato** [comment]
I think this should be faced urgently cause version 17.0 contains privacy manifest which is required by Apple since 1 May to deploy app on app store.
https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#1700

As you see here facebook packages are among the third party sdk under scrutiny 
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by greymag** [comment]
You are right, and I intend to release a new version of the plugin as soon as possible.

But if you are verifying the token on the backend, you will need to implement Limited Login token verification after updating the plugin in your app. 

For now, we decided to try to include the necessary entries in the application's privacy manifest and use a previous version of the FB SDK. We'll see if this works for Apple.

**Comment by greymag** [comment]
Released in [v2.0.0](https://pub.dev/packages/flutter_login_facebook/versions/2.0.0). Pay attention to the breaking changes described in Changelog.
