### ISSUE TITLE
How to get UserAboutMe API after permission is enabled

### ISSUE THREAD

**Issue by ram231** [Innim/flutter_login_facebook#13]
I've inspected the source code and found nothing about the **About Me** API. Is there plans on creating an `await fb.getUserAboutMe()` API?

**Comment by greymag** [comment]
Hey! 

The plugin is not initially for wide using Facebook SDK, it's just for login and get some basic information. Basic information - it's data, which Facebook provides in `Profile` instance ([FBSDKProfile.h](https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/FBSDKProfile.h)).

We may change it in future, but for now it's not planned.

But you still can load any information using Graph API request (for example with [http](https://pub.dev/packages/http) package).

Example:
```dart
import 'package:http/http.dart' as http;

// ...

// Log In
final loginRes = await plugin.logIn();

// Make request to Graph API
final res = await http.get(
    'https://graph.facebook.com/v7.0/me?fields=name,first_name,last_name&access_token=${loginRes.accessToken.token}');

// You'll get JSON response
print(res.body);
// Output: {"name":"Alex Novikov","first_name":"Alex","last_name":"Novikov","id":"2352327164341175"}

// You can parse it in Map and process as needed
final data = json.decode(res.body);
```
