### ISSUE TITLE
[Question] About CI/CD Build for key hashes

### ISSUE THREAD

**Issue by ram231** [Innim/flutter_login_facebook#15]
I don't understand what this meant
> ⚠️ Important! You should add key hashes for every build variants. E.g. if you have CI/CD which build APK for testing with it's own cerificate (it may be auto generated debug cetificate or some another) than you should add it's key too.

Do you have an example project(specifically in codemagic) that generates key hashes every build?

**Comment by greymag** [comment]
Hi!

I'll try to explain.

Let's see:
1. When you (or CI/CD) builds application - Android SDK use some certificate to sing it.
2. You can explicitly provide certificate in your gradle script with property `storeFile` of `signingConfigs`. But mostly common you provide only release certificate, and for debug is used [auto generated certificate](https://developer.android.com/studio/publish/app-signing#debug-mode). 
3. Auto generated certificate is created on local machine and didn't shared. So on **every** machine will be different get
certificate.
4. Facebook SDK uses key hashes to verify your app, i. e. if you install app with certificate which hash is not added to Facebook, then verification will be failed.

Summarizing. You should create key hashes for every debug certificate on every machine which makes **debug** build. Or you can provide explicitly single certificate for debug build and use it.

> Do you have an example project(specifically in codemagic) that generates key hashes every build?

No, I'm not using CodeMagic. But pay attention - not every build, but every certificate which used for build.
