### ISSUE TITLE
[Question] How to interact with firebase_auth?

### ISSUE THREAD

**Issue by AlainHsu** [Innim/flutter_login_facebook#16]
Hi, i am using firebase auth in my flutter project, i am looking solution for facebook login. Can i use this plugin with firebase_auth?

BTW, i am very appreciate your Readme guide of the plugin, it's very helpful for me, thank you very much!

**Comment by greymag** [comment]
Hi!

That's an interesting question =) I'm not familiar with Firebase Auth feature, but I have plans to look at it. So I will try to implement facebook login with firebase auth due next week.

**Comment by diego-lipinski-de-castro** [comment]
Check this gist ive made https://gist.github.com/diego-lipinski-de-castro/c8af7ecbc49129d545f494cf1415a590
