### ISSUE TITLE
Fackbook Login is currently unavailable for this app

### ISSUE THREAD

**Issue by AlainHsu** [Innim/flutter_login_facebook#17]
I got this error in the facebook login webpage, is there anything wrong with my facebook configuration?

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-17 at 16 01 11](https://user-images.githubusercontent.com/13879077/87763181-f4e2ed80-c846-11ea-9c77-9a53e5d496d5.png)

**Comment by greymag** [comment]
Hi. Looks like you didn't setup Facebook app. Check out this [article](https://medium.com/@greymag/add-facebook-login-in-your-flutter-app-5172b034aa7d)
