### ISSUE TITLE
Plugin only work when there is no FB app.

### ISSUE THREAD

**Issue by ycv005** [Innim/flutter_login_facebook#18]
Hey, recently I have release my app on Play store and eariler before release, I was testing on my phone(with no FB app install) and now, my colleague are saying FB sign_in is not working. 
And when I check into their phone, I found that the issue was because of the FB app. Then, I uninstall the FB app and after that FB sign_in was working. Following is the Error when sign_in was done when FB app was install.

![image](https://user-images.githubusercontent.com/26734819/88403476-3bf25500-cdea-11ea-9a2b-17c98c954a57.png)

Note - FB app (Facebook app)

**Comment by varundroid** [comment]
Did you add your colleagues as testers from your Facebook app dashboard?

**Comment by ycv005** [comment]
From FB dashboard, it is on Live, and only setup I have done in starting that was said in plugin's README/Installation guide. How to set it for live? But Again question arise that how it is working in my colleague after uninstalling FB app.

**Comment by ycv005** [comment]
Sorry for pinging you here, and thanks for creating great plugin. Do you have any idea- @greymag Thanks

**Comment by ycv005** [comment]
Ok, I found the solution, that is I need to add the release key hash of my app to the facebook developer.

**Comment by Sergioc013** [comment]
Hi @ycv005 , I am getting the same problem. Could you please explain to me, how to generate the hash keys? Thanks

**Comment by greymag** [comment]
@Sergioc013 See [README](https://github.com/Innim/flutter_login_facebook#setup-facebook-app) and follow by links to [documentation](https://developers.facebook.com/docs/facebook-login/android?locale=en_US#6--provide-the-development-and-release-key-hashes-for-your-app).

**Comment by Sergioc013** [comment]
@greymag Hi, thanks for your response. I followed the documentation but it still does not work, I added the debug and release hash keys but I still get the same message as seen in the screenshot that @ycv005 attached. I get the same behavior, if I uninstall it the Facebook app works correctly, however, as soon as I install it it stops working.

**Comment by greymag** [comment]
Do you have this behaviour when you install debug version of your app or only when you install from Google Play?

**Comment by Sergioc013** [comment]
@greymag  Yes, the error was in debugging and also when I installed it from Google Play, I was able to fix it with the hash keys. I generated hash keys with the command available for linux

echo "{sha1key}" | xxd -r -p | openssl base64

When I did it with the command that the documentation offers for windows, the generated hash keys did not work.

However, now when I tap the Login button with Facebook, it enters the app, without asking for credentials and without even showing the login confirmation or cancellation screen. Just log in and allow you to login without problems, I don't know if this behavior is fine for security reasons.

**Comment by ycv005** [comment]
Link- https://medium.com/@akashmahali/facebook-login-google-sign-in-not-working-on-android-app-in-production-5febd9537f92
https://medium.com/mindorks/generate-hash-key-for-facebook-and-sha-1-key-for-google-maps-in-android-studio-48d92e4f3c05
@greymag Hope this will help or other upcoming visitor.
