### ISSUE TITLE
Facebook SDK initialisation error

### ISSUE THREAD

**Issue by varundroid** [Innim/flutter_login_facebook#19]
Hi, thanks for this amazing plugin, really appreciate your contribution to the community.

I followed the setup instructions that were provided in readme, for iOS everything went smooth, no hiccups at all. But for Android, app is crashing with the following - 

 `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.example.app.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.`

Any idea why this will happen? I was hoping not to add the separate dependency in Android project, let me know if I need to do so.

Thanks

**Comment by greymag** [comment]
Hey!

You do not need to add the separate dependency in Android project. You only need to setup manifest and resources, as described in [Edit Your Resources and Manifest](https://github.com/Innim/flutter_login_facebook#edit-your-resources-and-manifest) section. Check if your missed `meta-data`:

```xml
<meta-data android:name="com.facebook.sdk.ApplicationId" 
        android:value="@string/facebook_app_id"/>
```

or value of id in `string.xml`

**Comment by varundroid** [comment]
Yup, I followed the given instructions on Android but as soon as I add the plugin to the project and run it on Android, I get gradle errors. I have put some time today to investigate this, will get back to you with my findings.

**Comment by varundroid** [comment]
Hi, I reverted my branch and restarted the setup and to my surprise, it all went okay this time. Not sure what did I do wrong last time, but anyways, all good now. Thanks for helping me out.

**Comment by onatcipli** [comment]
I'm getting the same error (`FacebookSdk.sdkInitialize()`), I just upgraded our project version to `3.3.3` also upgraded `flutter_login_facebook` plugin version to `^1.6.0`

Do you have some specific things to fix this issue?  @varundroid 


```
E/AndroidRuntime(20048): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.saytv.app/net.saytv.app.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/AndroidRuntime(20048): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime(20048): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(20048): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(20048): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(20048): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(20048): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(20048): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20048): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(20048): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(20048): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20048): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(20048): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(20048): Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/AndroidRuntime(20048): 	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
E/AndroidRuntime(20048): 	at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
E/AndroidRuntime(20048): 	at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
E/AndroidRuntime(20048): 	at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
E/AndroidRuntime(20048): 	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin._setActivity(FlutterLoginFacebookPlugin.java:70)
E/AndroidRuntime(20048): 	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin.onAttachedToActivity(FlutterLoginFacebookPlugin.java:39)
E/AndroidRuntime(20048): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:351)
E/AndroidRuntime(20048): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:324)
E/AndroidRuntime(20048): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:194)
E/AndroidRuntime(20048): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(20048): 	at android.app.Activity.performCreate(Activity.java:7994)
E/AndroidRuntime(20048): 	at android.app.Activity.performCreate(Activity.java:7978)
E/AndroidRuntime(20048): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(20048): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(20048): 	... 11 more

```

**Comment by kamxy** [comment]
> I'm getting the same error (`FacebookSdk.sdkInitialize()`), I just upgraded our project version to `3.3.3` also upgraded `flutter_login_facebook` plugin version to `^1.6.0`
> 
> Do you have some specific things to fix this issue? @varundroid
> 
> ```
> E/AndroidRuntime(20048): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.saytv.app/net.saytv.app.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
> E/AndroidRuntime(20048): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
> E/AndroidRuntime(20048): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
> E/AndroidRuntime(20048): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
> E/AndroidRuntime(20048): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime(20048): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime(20048): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
> E/AndroidRuntime(20048): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(20048): 	at android.os.Looper.loop(Looper.java:223)
> E/AndroidRuntime(20048): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
> E/AndroidRuntime(20048): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(20048): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> E/AndroidRuntime(20048): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> E/AndroidRuntime(20048): Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
> E/AndroidRuntime(20048): 	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
> E/AndroidRuntime(20048): 	at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
> E/AndroidRuntime(20048): 	at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
> E/AndroidRuntime(20048): 	at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
> E/AndroidRuntime(20048): 	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin._setActivity(FlutterLoginFacebookPlugin.java:70)
> E/AndroidRuntime(20048): 	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin.onAttachedToActivity(FlutterLoginFacebookPlugin.java:39)
> E/AndroidRuntime(20048): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:351)
> E/AndroidRuntime(20048): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:324)
> E/AndroidRuntime(20048): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:194)
> E/AndroidRuntime(20048): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
> E/AndroidRuntime(20048): 	at android.app.Activity.performCreate(Activity.java:7994)
> E/AndroidRuntime(20048): 	at android.app.Activity.performCreate(Activity.java:7978)
> E/AndroidRuntime(20048): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
> E/AndroidRuntime(20048): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
> E/AndroidRuntime(20048): 	... 11 more
> ```

same issue

**Comment by onatcipli** [comment]
I just get over this issue by adding the following code to `android/app/src/main/AndroidManifest.xml`

```
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
            
        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token" />
```

especially, `ClientToken` one. you may read again the [getting started part again for migration](https://pub.dev/packages/flutter_login_facebook)

hope it helps!

**Comment by greymag** [comment]
Also check [UPGRADE.md](https://github.com/Innim/flutter_login_facebook/blob/master/UPGRADE.md) when updating the version.
