### ISSUE TITLE
Android onActivityResult doesn't work in other plugins

### ISSUE THREAD

**Issue by dikiyPetr** [Innim/flutter_login_facebook#24]
other facebook plugins (social_share_plugin) that use onActivityResult () can't get the result, because (flutter_login_facebook) override  this method

**Comment by SecondStream** [comment]
Hello! We've checked your issue. social_share_plugin and flutter_login_facebook works fine together.

And `onActivityResult()` is handled too. I added to `SocialSharePlugin.onActivityResult()`:
`Log.d("SocialSharePlugin", requestCode + " " + resultCode + " " + data);`

In the log after share:
> 2020-08-14 16:41:46.373 3702-3702/ru.innim.flutter_login_facebook_example D/SocialSharePlugin: 64207 -1 Intent { (has extras) }
2020-08-14 16:41:46.383 3702-3702/ru.innim.flutter_login_facebook_example D/SocialSharePlugin: Sharing successfully done.
