### ISSUE TITLE
Expose the GraphAPI endpoint

### ISSUE THREAD

**Issue by fxsalazar** [Innim/flutter_login_facebook#26]
Couldn't be a good idea to expose a generic method to make request to the GraphAPI using the `GraphRequest`?

Primarily, this will let the managing of the token on the native SDK side; and because that any request has to be done with a token, which the login is already providing and holding, this will ease the implementation of other Facebook's non-existent components. ie. PagesAPI, EventsAPI, etc.

**Comment by greymag** [comment]
Hey!

The plugin purpose is just log in with Facebook account and get some basic information for displaying in the app. It was not intent to implement Graph API or another SDK methods. But if you implement it I'll be happy to accept your PR =)

Also anyone can implement methods for making requests to the GraphAPI as an extension method in their own project. Or just making graph api request with `http` or `dio` as I suggest [here](https://github.com/Innim/flutter_login_facebook/issues/13#issuecomment-655598424).

**Comment by fxsalazar** [comment]
> as an extension method

How so?

I did my implementation using `http` and is working well. I just thought it could be a good idea to let the SDK handle that for the client.

I do agree that for the other SDKs, other packages should be created as they do.

**Comment by greymag** [comment]
> How so?

https://dart.dev/guides/language/extension-methods
