### ISSUE TITLE
No platform was specified cocoapods error

### ISSUE THREAD

**Issue by junca8** [Innim/flutter_login_facebook#28]
I'm getting the following error when adding `flutter_login_facebook` to my pubspec.yaml:

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a
    platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

After creating a new flutter project, the only change I made was adding `flutter_login_facebook: ^0.2.1` to my pubspec.yaml file. Any ideas on what's happening?

**Comment by greymag** [comment]
Hey! Set minimum iOS to 9.0. It's required by iOS part of the plugin.
