### ISSUE TITLE
Submission to appstore with this plugin complains that a deprecated UIWebView API is being used

### ISSUE THREAD

**Issue by MsXam** [Innim/flutter_login_facebook#3]
Hi - just testing out the plugin on both iOS and Android. In both versions - the plugin works perfectly. Tested in both Java/Kotlin built projects and also OBJ-C/Swift built projects.

I did have some issues with my app building properly in iOS and needed to POD install FBSDKCoreKit/LoginKit 7.0.0, then flutter clean and then build again...

Looking in podfile.lock, appears to use latest 7.0.0 API  :- 

```
 FBSDKCoreKit (7.0.0):
    - FBSDKCoreKit/Basics (= 7.0.0)
    - FBSDKCoreKit/Core (= 7.0.0)
  - FBSDKCoreKit/Basics (7.0.0)
  - FBSDKCoreKit/Core (7.0.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (7.0.0):
    - FBSDKLoginKit/Login (= 7.0.0)
  - FBSDKLoginKit/Login (7.0.0):
    - FBSDKCoreKit (~> 7.0.0)
```

So - whats the issue? Well , submitting an app built with this plugin - I get deprecated warnings : 

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "SaxySusie4You" 0.0.14 (2). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. 
Instead, use WKWebView for improved security and reliability. Learn more 
(https://developer.apple.com/documentation/uikit/uiwebview).
```

**Comment by greymag** [comment]
Hi! Thanks for the information, we take a look.

Can you please open Xcode project folder (`{your flutter project}/ios/`) in Terminal, execute `grep -r "UIWebView" .` and post output here?

**Comment by greymag** [comment]
I am just submit my application with facebook login in App Store and didn't get deprecated warning. Are you sure that the problem with plugin? Any chance it can be problem with some another feature? Can you do  `grep -r "UIWebView" . ` in project folder, as described above?

**Comment by MsXam** [comment]
hey there !

You are absolutely right . **My bad** . It would appear that old facebook sdk was being referred in my podfile.lock file even though I was using your plugin. I removed the lock file, updated the pod cache , deintegrated pods, then did a complete pod install.

After I did this, I created an archive and submitted it. There was no warning this time.

Thank you so much - the plugin is perfect.

P.s do you have plans for other providers ? i.e Twitter etc ?

**Comment by greymag** [comment]
Happy to hear that!

> P.s do you have plans for other providers ? i.e Twitter etc ?

Now we developing plugin for login via Vk.com. No plans about Twitter at the moment.
