### ISSUE TITLE
 PlatformException(INTERRUPTED, Waiting login result was been interrupted!, null)

### ISSUE THREAD

**Issue by shiwam77** [Innim/flutter_login_facebook#30]
Getting following platform Exception error on emulator after clicking on continue .
![Screenshot_1600183039](https://user-images.githubusercontent.com/42408353/93229888-cf1a8c00-f796-11ea-8fed-8ee9acbd420a.png)
.Please guide how to resolve this. 

```
I/flutter ( 7427): PlatformException(INTERRUPTED, Waiting login result was been interrupted!, null)
I/flutter ( 7427): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
I/flutter ( 7427): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
I/flutter ( 7427): <asynchronous suspension>
I/flutter ( 7427): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
I/flutter ( 7427): #3      FacebookLogin.logIn (package:flutter_login_facebook/src/facebook_login.dart:154:10)
I/flutter ( 7427): #4      FacebookGraph.newInitiateOAuthLogin (package:spock/clients/facebook.dart:42:51)
I/flutter ( 7427): #5      _LogInRouteState._continueWithFacebook (package:spock/routes/login/login.dart:186:5)
I/flutter ( 7427): #6      _LogInRouteState.build.<anonymous closure>.<anonymous closure> (package:spock/routes/login/login.dart:115:23)
I/flutter ( 7427): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
I/flutter ( 7427): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
I/flutter ( 7427): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
I/flutter ( 7427): #10     TapGestureRecogniz
```

**Comment by greymag** [comment]
Hi!

Looks like you call login twice. You can't call login second time while first call is not complete.

**Comment by 5hirish** [comment]
Hi @greymag thank you for responding. We are only calling it once, after a button click. What else could be the reason?

**Comment by greymag** [comment]
Maybe your handler invokes another time when user tap "continue" in facebook window? Try to add prints right before calling `FacebookLogin.logIn` and see if it's actually called once. Because your stacktrace says that was a login call, while you writing that this error happens after you click "continue" (so it shouldn't be a login call).

**Comment by shiwam77** [comment]
Actually in physical devices , this page don't even appear.In emulator ,when we click on "contiue With facebook" button, this page appear then we click on  continue then it navigate us back again the "contiue With facebook" button  then again click on  "contiue With facebook" button then i got this stacktrace.

**Comment by greymag** [comment]
Can you please send me a gif or a video of whole process?

**Comment by shiwam77** [comment]
Emulator:-

![ezgif com-optimize](https://user-images.githubusercontent.com/42408353/93238076-abf4da00-f7a0-11ea-9e4a-67ca41e0495d.gif)


In physical Device:-

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42408353/93238616-671d7300-f7a1-11ea-86a2-898183d43c77.gif)

**Comment by greymag** [comment]
Oh, I see. Looks like your app does not handle intent from facebook. 

Check your manifest and `strings.xml` https://github.com/Innim/flutter_login_facebook#edit-your-resources-and-manifest 

If that ok - then check Facebook app settings https://github.com/Innim/flutter_login_facebook#setup-facebook-app

**Comment by 5hirish** [comment]
Figured out the issue. This package requires: 
[Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)

Please include this note in your ReadMe. Thanks!

**Comment by greymag** [comment]
Fully remove support of android embedding v1 since [1.4.0](https://pub.dev/packages/flutter_login_facebook/versions/1.4.0).
Note added in Readme.
