### ISSUE TITLE
No Email on Android / Graph API

### ISSUE THREAD

**Issue by shredding** [Innim/flutter_login_facebook#31]
I have problems accessing the email from the access token, both on the server side and on android. However, it does work on iOS.

I am following the plain example from your code and I can see in my facebook settings that the app has access to the email (and this is correct, as it works on iOS).

I digged into the iOS and Android code and can't spot the difference. 

Is this a known problem?

**Comment by greymag** [comment]
Hey!

My apologies for such late answer. Is problem still relevant? 

I'd try to reproduce the problem and I can't - I got email both on iOS and Android. 

Try to enabled debug mode
```dart
final plugin = FacebookLogin(debug: true);
```

and see log when you call `plugin.getUserEmail()`. What it says?

**Comment by greymag** [comment]
Since there are no more complains about getting email, I am close that issue. If anyone face the problem again - feel free to reopen it.
