### ISSUE TITLE
Crashes when used with video_player plugin

### ISSUE THREAD

**Issue by HiroshiHorie** [Innim/flutter_login_facebook#33]
I found out that video_player package crashes with the following error
only when I use this package.

File: video_player_platform_interface-2.2.0/lib/messages.dart
```
PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))
```

I wasn't sure where to report this. But this only happens when i use flutter_login_facebook.

regards

**Comment by greymag** [comment]
Hey!

Thanks for the report! I'll take a look.

**Comment by HiroshiHorie** [comment]
@greymag 
I like this plugin I hope there's a way to make it work. Even a work around.
Thanks!

**Comment by greymag** [comment]
@HiroshiHorie 
I can't reproduce the bug. Can you please help me with that:

- On what OS the problem happens: iOS, Android, both?
- In what moment you see the exception in log? Right on launch, or when you loading video, or when you try to play it, or maybe when you try to log in with Facebook?

And if you could provide a small example project with a problem (for example on the `example` project of this plugin) it will be very helpful.

**Comment by HiroshiHorie** [comment]
I appreciate the effort you looking into this. I'm having trouble to reproduce it also.
Might not be related to your plugin. I'm sorry in that case. I will close this until I collect more info. thanks!
