### ISSUE TITLE
Facebook Logout Issue

### ISSUE THREAD

**Issue by MuhammadHassanRazaa** [Innim/flutter_login_facebook#44]
Facebook is not logging out properly even after clicking the logout button. I have used the following code:
``` final facebookLogin = FacebookLogin();
    await facebookLogin.logOut();
    await _firebaseAuth.signOut();
```

I have also tried deleting the user from the firebase account, but when I clicked on the SIgn in button again, it added the same user in firebase. I guess it is because I have the Facebook app installed on my phone, I have tried deleting the Facebook app and it worked properly.

P.S I am using android.

**Comment by greymag** [comment]
Hey! What exactly do you mean by "not logging out properly"?

Also, please check out my answer in similar issue  https://github.com/Innim/flutter_login_facebook/issues/11#issuecomment-653729451

**Comment by greymag** [comment]
No answer, so I assume that problem are resolved and close the issue.

**Comment by aperezhra** [comment]
I opened a new issue for this same logout scenario.

https://github.com/Innim/flutter_login_facebook/issues/48
