### ISSUE TITLE
SharedPreference not working with this package?

### ISSUE THREAD

**Issue by developerflutter** [Innim/flutter_login_facebook#45]
SharedPreference not working with this package! any solution?

**Comment by greymag** [comment]
Hey! I'm using shared_preferences and this package in several my projects - it's all working. Can you please describe what is not working? Which error you get? Which versions of the packages you use? If you can reproduce the issue on example project - it will be great!

**Comment by developerflutter** [comment]
I am using shared_preferences: ^2.0.5 , flutter_login_facebook: ^1.0.1.

Getting error as MissingPluginException (MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences))

**Comment by greymag** [comment]
Thanks for the answer!

I just add dependency of `shared_preferences: ^2.0.5` in example project and SharedPreference is working. I think it's more complicated problem. Maybe there is an exception in plugin registration - can you check out the logcat for any error messages on start?

Also is this error happens both iOS and Android or only on specific platform?

**Comment by AasharWahla** [comment]
I am also facing this error, and it is only specific to android. Working best for iOS. 
I am trying to use it with google_sign_in ^5.0.2
And the error is the same as given above.

**Comment by AasharWahla** [comment]
`MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)`
This is the error, I am facing. The app works fine if I remove flutter_login_facebook plugin.

**Comment by greymag** [comment]
Hey @AasharWahla! Thanks for the report. Same question: can you check out the logcat for any error messages on start?

The deal is that error most likely just a result of some exception during plugin registration process on app launch.

**Comment by AasharWahla** [comment]
can you tell me how to check logcat?

**Comment by greymag** [comment]
If you use Android Studio you should have a tab at the bottom 
![](https://d.pr/i/rJIGgi+)

Or you can use command line tool https://developer.android.com/studio/command-line/logcat

**Comment by fleoparra** [comment]
Hi, I had a similar problem, but with another library (google_mobile_ads) the error that logcat show was:
I/FacebookInitProvider: Failed to auto initialize the Facebook SDK
    A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.

After put facebook app id the problem was solved.

**Comment by greymag** [comment]
Hey! Thank to figure it out. That's correct - you **must** add ID in your manifest. It's in [README](https://github.com/Innim/flutter_login_facebook#edit-your-resources-and-manifest).

@AasharWahla @developerflutter is that your case too?

> It is weir that a facebook initialization error show an error in flutter with another library.

It's not weird =) There are an exception during app start up, which interrupts plugins registration process. This exception thrown by Facebook SDK and informs you that application is not configured properly.

**Comment by zeevgrim** [comment]
fix with - 

Open your /android/app/src/main/res/values/strings.xml file, or create one if it doesn't exists.
Add the following (replace {your-app-id} with your facebook app Id):
```
  <string name="facebook_app_id">{your-app-id}</string>
  <string name="fb_login_protocol_scheme">fb{your-app-id}</string>
```
Here one example of strings.xml:
```
<resources>
  <string name="app_name">Flutter Facebook Auth Example</string>
  <string name="facebook_app_id">1365719610250300</string>
  <string name="fb_login_protocol_scheme">fb1365719610250300</string>
</resources>
```

Open the /android/app/src/main/AndroidManifest.xml file.

Add the following uses-permission element after the application element

`<uses-permission android:name="android.permission.INTERNET"/>
`

Add the following meta-data element, an activity for Facebook, and an activity and intent filter for Chrome Custom Tabs inside your application element

```
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

 <activity android:name="com.facebook.FacebookActivity"
     android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
     android:label="@string/app_name" />
 <activity
     android:name="com.facebook.CustomTabActivity"
     android:exported="true">
     <intent-filter>
         <action android:name="android.intent.action.VIEW" />
         <category android:name="android.intent.category.DEFAULT" />
         <category android:name="android.intent.category.BROWSABLE" />
         <data android:scheme="@string/fb_login_protocol_scheme" />
     </intent-filter>
 </activity>
```

**Comment by greymag** [comment]
Yep, that's all in [README](https://github.com/Innim/flutter_login_facebook#edit-your-resources-and-manifest). Just follow instructions when you adding Facebook Logins support and there will be no problems.
