### ISSUE TITLE
facebook invalid key hash

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [Innim/flutter_login_facebook#46]
![kFasB](https://user-images.githubusercontent.com/49102327/118064877-f6207080-b3ac-11eb-95a8-17f4b5ba7c37.jpeg)
 

how can i solve this problem?

**Comment by greymag** [comment]
Hey. You didn't add key hash in Facebook App Settings. See [README](https://github.com/Innim/flutter_login_facebook#setup-facebook-app), Step 6 in Android setup section.
