### ISSUE TITLE
AX Lookup problem

### ISSUE THREAD

**Issue by desmeit** [Innim/flutter_login_facebook#47]
I get the following error:

`[AXRuntimeCommon] Unknown client: Runner
[tcp] tcp_input [C8.1:3] flags=[R] seq=1710933642, ack=0, win=0 state=CLOSED rcv_nxt=1710933642, snd_una=2129208749
[tcp] tcp_input [C8.1:3] flags=[R] seq=1710933642, ack=0, win=0 state=CLOSED rcv_nxt=1710933642, snd_una=2129208749
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:1846 (
        0   AXRuntime                           0x00000001a237f330 4054936E-248B-3ADB-81B1-0AA941922C9C + 365360
        1   AXRuntime                           0x00000001a232a150 _AXGetPortFromCache + 560
        2   AXRuntime                           0x00000001a232b7e0 AXUIElementPerformFencedActionWithValue + 464
        3   UIKit                               0x00000001ce9da324 6CE533D0-61DA-329E-B111-05CD5C09CC2E + 901924
        4   libdispatch.dylib                   0x0000000182799a54 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 10836
        5   libdispatch.dylib                   0x000000018279b7ec FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 18412
        6   libdispatch.dylib                   0x00000001827a2fd4 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 49108
        7   libdispatch.dylib                   0x00000001827a3bd0 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 52176
        8   libdispatch.dylib                   0x00000001827ae48c FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 95372
        9   libsystem_pthread.dylib             0x00000001ce6e67a4 _pthread_wqthread + 276
        10  libsystem_pthread.dylib             0x00000001ce6ed74c start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:1846 (
        0   AXRuntime                           0x00000001a237f330 4054936E-248B-3ADB-81B1-0AA941922C9C + 365360
        1   AXRuntime                           0x00000001a232a150 _AXGetPortFromCache + 560
        2   AXRuntime                           0x00000001a232b7e0 AXUIElementPerformFencedActionWithValue + 464
        3   UIKit                               0x00000001ce9da324 6CE533D0-61DA-329E-B111-05CD5C09CC2E + 901924
        4   libdispatch.dylib                   0x0000000182799a54 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 10836
        5   libdispatch.dylib                   0x000000018279b7ec FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 18412
        6   libdispatch.dylib                   0x00000001827a2fd4 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 49108
        7   libdispatch.dylib                   0x00000001827a3bd0 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 52176
        8   libdispatch.dylib                   0x00000001827ae48c FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 95372
        9   libsystem_pthread.dylib             0x00000001ce6e67a4 _pthread_wqthread + 276
        10  libsystem_pthread.dylib             0x00000001ce6ed74c start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:1846 (
        0   AXRuntime                           0x00000001a237f330 4054936E-248B-3ADB-81B1-0AA941922C9C + 365360
        1   AXRuntime                           0x00000001a232a150 _AXGetPortFromCache + 560
        2   AXRuntime                           0x00000001a232b7e0 AXUIElementPerformFencedActionWithValue + 464
        3   UIKit                               0x00000001ce9da324 6CE533D0-61DA-329E-B111-05CD5C09CC2E + 901924
        4   libdispatch.dylib                   0x0000000182799a54 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 10836
        5   libdispatch.dylib                   0x000000018279b7ec FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 18412
        6   libdispatch.dylib                   0x00000001827a2fd4 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 49108
        7   libdispatch.dylib                   0x00000001827a3bd0 FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 52176
        8   libdispatch.dylib                   0x00000001827ae48c FFC93E7E-8360-32A0-9EB5-FE3761B8C90A + 95372
        9   libsystem_pthread.dylib             0x00000001ce6e67a4 _pthread_wqthread + 276
        10  libsystem_pthread.dylib             0x00000001ce6ed74c start_wqthread + 8
)`

```
// Facebook
  Future fbSignIn() async {
    final fb = FacebookLogin();

// Log in
    final res = await fb.logIn(permissions: [
      FacebookPermission.publicProfile,
      FacebookPermission.email,
    ]);

// Check result status
    switch (res.status) {
      case FacebookLoginStatus.success:
        // Logged in

        // Send access token to server for validation and auth
        final FacebookAccessToken accessToken = res.accessToken;
        final AuthCredential authCredential =
            FacebookAuthProvider.credential(accessToken.token);
        final result =
            await FirebaseAuth.instance.signInWithCredential(authCredential);

        // Get profile data
        final profile = await fb.getUserProfile();
        print('Hello, ${profile.name}! You ID: ${profile.userId}');

        // Get user profile image url
        final imageUrl = await fb.getProfileImageUrl(width: 100);
        print('Your profile image: $imageUrl');

        // Get email (since we request email permission)
        final email = await fb.getUserEmail();
        // But user can decline permission
        if (email != null) print('And your email is $email');

        break;
      case FacebookLoginStatus.cancel:
        // User cancel log in
        break;
      case FacebookLoginStatus.error:
        // Log in failed
        print('Error while log in: ${res.error}');
        break;
    }
  }
}
```

The login with firebase ist working but I got this error. Any ideas?

**Comment by greymag** [comment]
Hey!  Is that problem only with facebook login, or with any request? 

I'm not much in native iOS development, so i'm not sure what is that error about.

**Comment by greymag** [comment]
No answer, so I'm closing the issue for now. Feel free to open it if error still exist.
