### ISSUE TITLE
Unable to login with a differente account after logout

### ISSUE THREAD

**Issue by aperezhra** [Innim/flutter_login_facebook#48]
I'm trying to login with a different facebook account after logging out, but every time I Login, the logIn method asks to continue with the previous logged in user, without asking for credentials of credentials, not even for the previously logged in user.

The accessToken hasCode is different before and after loguOut, but the app always tries to re-login with the same account.

The only way for me to login in with a different account is IF i delete Chrome's cache. 

**Snippet**
```
  logout() async {

    // Sign Out from Facebook
    if (await isFacebookSignedIn()) {
      print("Facebook Token Before: ${facebookSignIn.accessToken.hashCode}");
      print("Sign Out from Facebook");
      await facebookSignIn.logOut();
      print("Facebook Token After: ${facebookSignIn.accessToken.hashCode}");
    }

    // Log Out from Firebase
    print("Firebase User Before: ${authService.currentUser.hashCode}");
    print("Log out from Firebase");
    authService.logOut();
    print("Firebase User After: ${authService.currentUser.hashCode}");
  }

```
**Log Trace**
> flutter: Facebook - Token Before: FacebookAccessToken(token: EAAM1VXnjookBADNaf#####WQBipMCZBXCRrAqz1QZATOKR5nOjOeR78IcOht1gDAsVg1EYZAeccBFKb4GWnXGfjVXT3H1P3dilV95RA5QdZAF9IFU6JzgQCI8sGEp#####KyaO5YAHadJnVzEOKZAxZBmo23YeZAiU7qr4#####Rts7, userId: 10158454090076589, expires: 2021-07-30 21:12:05.921Z, permissions: [public_profile, email, openid], declinedPermissions: [])
> flutter: Facebook - Sign Out
> flutter: Facebook - Token After: null
> flutter: Firebase - User Before: User(displayName: Angel Perez, email: #####hotmail.com, emailVerified: false, isAnonymous: false, metadata: UserMetadata(creationTime: 2021-05-26 19:57:58.311, lastSignInTime: 2021-05-31 16:12:07.392), phoneNumber: null, photoURL: https://graph.facebook.com/10158#####6589/picture, providerData, [UserInfo(displayName: ##### ##### email: #####hotmail.com, phoneNumber: null, photoURL: https://graph.facebook.com/10158*****6589/picture, providerId: facebook.com, uid: 10158#####6589)], refreshToken: , tenantId: null, uid: fCpoE9zN#####HtJq4ij2)
> flutter: Firebase - Log Out
> flutter: Firebase - User After: null

**Picture**
![image](https://user-images.githubusercontent.com/82792492/119664901-72797180-bdf9-11eb-9f2c-719204433e70.png)

**Comment by greymag** [comment]
Hey! Are you sure that is plugin problem? Looks like a Facebook SDK behaviour.

**Comment by aperezhra** [comment]
> Hey! Are you sure that is plugin problem? Looks like a Facebook SDK behaviour.

Hi. Well, I'm not sure. I don't have enough FB SDK experience to know it from the top of my head.

It's just curious and annoying the fact that a "logOut" action is not completely logging out - Based on the fact that a new login request:

1. Does not ask for user entry.
2. If you click continue, it logs you right back in without prompting for a any credentials.

Unless there's something I'm doing wrong (which is highly probable), this logOut behavior doesn't feel secure.

I checked the flutter plugin documentation and I just can't figure it out.

Bonus annoying point: A similar problem is encountered if you login with a user not registeres as a testing user. Apparently FB, logs you in correctly, but then rejects you due permissions. So you have to cancel the login process, getting a FacebookLoginStatus.cancel status, but when you try to log back in with different credentials, the login screen gets stuck with the "no testing user" permission denied message... so.. is it logged in or not...??

**Comment by jaasaria** [comment]
got the same issue here.

**Comment by aperezhra** [comment]
I edited/updated the Log Trace above.

Still getting the same response, not being able to login with a different account nor being able to enter credentials again.

**Comment by zhukeev** [comment]
Have you guys found a solution ?

**Comment by greymag** [comment]
This is expected behaviour from Facebook 
https://github.com/facebook/facebook-ios-sdk/issues/1513 

This is a little weird, but the most of users have just one Facebook account, so it's ok for them.

I'm closing this issue, because nothing we can do about it.

**Comment by aperezhra** [comment]
> This is expected behaviour from Facebook
> [facebook/facebook-ios-sdk#1513](https://github.com/facebook/facebook-ios-sdk/issues/1513)
> 
> This is a little weird, but the most of users have just one Facebook account, so it's ok for them.
> 
> I'm closing this issue, because nothing we can do about it.

Hello graymag, I understand your explaining about most users having one single account. But what about the huge security problem that this same “expected behavior” exposes by not even requesting the credentials of the  same user account after logging out? Is this also expected behavior? 

How is this plug-in going to document this known security issue if to the users if the bug just gets closed out without any action item?
AND will you ever report this insecure behavior to FB?

**Comment by greymag** [comment]
Hello @aperezhra!

> But what about the huge security problem that this same “expected behavior” exposes by not even requesting the credentials of the same user account after logging out? Is this also expected behavior?

When you "log out" in your app - you just clear current token (and session). But you doesn't logout from user's Facebook account. And yes, if user are logged in with his Facebook account, then he doesn't need to enter pass again. 

If user want to logout from Facebook - he need to log out in Safari/Chrome/Facebook app and that credentials will be requested.

> How is this plug-in going to document this known security issue if to the users if the bug just gets closed out without any action item?

I don't think this is security issue. As well as Facebook. 

> AND will you ever report this insecure behavior to FB?

I won't, but you can do it yourself, if you think that this is a problem.
