### ISSUE TITLE
Facebook photoURL not rendering properly after Firebase signInWithCredential (AuthCredential/UserCredential)

### ISSUE THREAD

**Issue by aperezhra** [Innim/flutter_login_facebook#49]
After logging in on Firebase using a Facebook AuthCredential obtained from a Facebook Token, the UserCredential's photoURL generates an incorrect URL that would not render a proper profile picture from Facebook.

Would this be a plugin bug? How can I confirm where in the process is the photoURL being set incorrectly?

```
        // Credential
        final AuthCredential credential =
            FacebookAuthProvider.credential(facebookToken.token);

        // Firebase Sign In
        final result = await authService.signInWithCredential(credential);

        print("UserCredential photoUrl \"${result.user.photoURL}\"");
        print(
            "getProfileUmageUrl: ${await facebookSignIn.getProfileImageUrl(width: 400)}");

```

Console output
```
flutter: UserCredential photoUrl "https://graph.facebook.com/**********/picture"
flutter: getProfileUmageUrl: https://graph.facebook.com/v9.0/**********/picture?access_token=EAAM1VXnjookBAO2*********rGtzx1x6Dmtb4Y96wVamw0B0kxU95dBZBOL3zqJGff9oMk15mI2hq2cgsSxNbk8rPaB77bA2K0UA9ApNhbPdE8V*******3vW53AdhPnZATJ8SI8w7NXceKSpZB9WzqZCliLA5q3ukVvKCIrWut8OQKQG3ZAo1W3vYZBugnwvg5Hf6ziIbtyWP0S&height=400&type=normal&width=400
```

The workaround is to capture the correct URL from getProfileImageUrl from the FacebookLogin instance and update the user profile with it.

```
    await _auth.currentUser
        .updateProfile(
            displayName: signInWithCredential.user.displayName,
            photoURL: await facebookSignIn.getProfileImageUrl(width: 400))
        .then((value) => null);
```

**Comment by greymag** [comment]
Hey!

As I see - `getProfileImageUrl()` returns a correct result. Honestly, I have no idea what is Firebase user instance returns =) Why you think that this is the plugin problem?

**Comment by aperezhra** [comment]
This used to work in previous versions of both Facebook and Firebase plugins.

There’s a generic implementation pattern to use Firebase as a some sort of credential store than creates the profiles based on the information provided by plugins as Facebook/Google/AppleId/etc.
This profiles are created using the information from the individual authentication providers.

**Comment by greymag** [comment]
Looks like a bug in firebase plugin https://github.com/FirebaseExtended/flutterfire/issues/3839

**Comment by aperezhra** [comment]
Hello Folks! 
Do you have any workaround for this?

I have a use case where I update firebase user's photoURL with the Facebook tokenized profile photo, but these changes are not reflected to my User stream until the next time log back in.

Please help.

**Comment by greymag** [comment]
Sorry, I'm not familiar with Firebase plugin, so I don't know how to update profile photo in their User stream properly.
