### ISSUE TITLE
login dialog is not showing

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Innim/flutter_login_facebook#51]
I took code from an example but login dialog does not come up

```
final fb = FacebookLogin();
    final facebookLoginResult = await fb.logIn(permissions: [
      FacebookPermission.publicProfile,
      FacebookPermission.email,
    ]);

```

just nothing happens...

**Comment by greymag** [comment]
Hello. Is any error in console or logcat?
Did you follow instructions in [README](https://github.com/Innim/flutter_login_facebook/blob/master/README.md) on setup application?

**Comment by vytautas-pranskunas-** [comment]
No there i sno error. 
Yes i followed instructions (partially because ostly intructions are same).
I have another plugin working (before that i had one more which is deprectaed now) and all works ok, But plugin that i am using is doing webview reidrect so i was willing to try yours hoping that you are showing modal.
Currently I am using this: https://pub.dev/packages/flutter_facebook_auth

**Comment by greymag** [comment]
@Sergioc013 any messages in logcat?

**Comment by Sergioc013** [comment]
@greymag None

**Comment by greymag** [comment]
@vytautas-pranskunas- @Sergioc013 Can you check last version? I updated Android SDK

**Comment by Sergioc013** [comment]
I was able to fix the error, there was a problem with the hash keys. Although I was generating them correctly with the Windows command, it didn't work for me, so I tried running the Linux command, and it generated some new keys with which the Facebook login did work.

**Comment by greymag** [comment]
Thanks for the answer!

**Comment by KuldeepAIP** [comment]
i am facing the same issue and i have generated development and release hash key and added in Facebook app settings but still i am getting this error with Facebook app while working fine with Web.

**Comment by chhily** [comment]
Hey! as in 08-22-2022, I facing the same problem. I already config everything according to doc.

**Comment by rsegecin** [comment]
Hi, you guys can open the Flutter generated android project on Android Studio and run its code from there to get logcat and see log details. I was just facing the same issue as it turns out at the beginning of this year facebook SDK 13 started to demand a Client Token see [Client Access Tokens](https://developers.facebook.com/docs/facebook-login/guides/access-tokens) so as I updated my App I had to include this token so the Facebook SDK would be properly initialized.
