### ISSUE TITLE
Won't compile for iOS

### ISSUE THREAD

**Issue by dmvvilela** [Innim/flutter_login_facebook#52]
I am using latest version and it won´t compile on iOS.

Errors:

/pub.dartlang.org/flutter_login_facebook-1.0.1/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:178:61: Type 'Profile' has no member 'PictureMode'

/pub.dartlang.org/flutter_login_facebook-1.0.1/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:199:11: Extra trailing closure passed in call

/pub.dartlang.org/flutter_login_facebook-1.0.1/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:197:26: Cannot convert value of type '[Permission]' to expected argument type '[String]'

/pub.dartlang.org/flutter_login_facebook-1.0.1/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:244:34: Value of type 'AccessToken' has no member 'permissions'

/pub.dartlang.org/flutter_login_facebook-1.0.1/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:245:42: Value of type 'AccessToken' has no member 'declinedPermissions'

Flutter doctor -v:

[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale pt-BR)
    • Flutter version 2.2.2 at /Users/danvilela/flutter
    • Framework revision d79295af24 (9 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/danvilela/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 68012A62-7148-434F-BCE6-79C6B9CC9875 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome
      91.0.4472.106

• No issues found!

**Comment by greymag** [comment]
Hey! Please, share what's in your `/ios/Podfile.lock`

**Comment by dmvvilela** [comment]
`PODS:
  - abseil/algorithm (0.20200225.0):
    - abseil/algorithm/algorithm (= 0.20200225.0)
    - abseil/algorithm/container (= 0.20200225.0)
  - abseil/algorithm/algorithm (0.20200225.0):
    - abseil/base/config
  - abseil/algorithm/container (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/base (0.20200225.0):
    - abseil/base/atomic_hook (= 0.20200225.0)
    - abseil/base/base (= 0.20200225.0)
    - abseil/base/base_internal (= 0.20200225.0)
    - abseil/base/bits (= 0.20200225.0)
    - abseil/base/config (= 0.20200225.0)
    - abseil/base/core_headers (= 0.20200225.0)
    - abseil/base/dynamic_annotations (= 0.20200225.0)
    - abseil/base/endian (= 0.20200225.0)
    - abseil/base/errno_saver (= 0.20200225.0)
    - abseil/base/exponential_biased (= 0.20200225.0)
    - abseil/base/log_severity (= 0.20200225.0)
    - abseil/base/malloc_internal (= 0.20200225.0)
    - abseil/base/periodic_sampler (= 0.20200225.0)
    - abseil/base/pretty_function (= 0.20200225.0)
    - abseil/base/raw_logging_internal (= 0.20200225.0)
    - abseil/base/spinlock_wait (= 0.20200225.0)
    - abseil/base/throw_delegate (= 0.20200225.0)
  - abseil/base/atomic_hook (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/base (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/log_severity
    - abseil/base/raw_logging_internal
    - abseil/base/spinlock_wait
    - abseil/meta/type_traits
  - abseil/base/base_internal (0.20200225.0):
    - abseil/base/config
    - abseil/meta/type_traits
  - abseil/base/bits (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/config (0.20200225.0)
  - abseil/base/core_headers (0.20200225.0):
    - abseil/base/config
  - abseil/base/dynamic_annotations (0.20200225.0)
  - abseil/base/endian (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/errno_saver (0.20200225.0):
    - abseil/base/config
  - abseil/base/exponential_biased (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/log_severity (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/malloc_internal (0.20200225.0):
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/raw_logging_internal
  - abseil/base/periodic_sampler (0.20200225.0):
    - abseil/base/core_headers
    - abseil/base/exponential_biased
  - abseil/base/pretty_function (0.20200225.0)
  - abseil/base/raw_logging_internal (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/log_severity
  - abseil/base/spinlock_wait (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/core_headers
    - abseil/base/errno_saver
  - abseil/base/throw_delegate (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/container/compressed_tuple (0.20200225.0):
    - abseil/utility/utility
  - abseil/container/inlined_vector (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/container/inlined_vector_internal
    - abseil/memory/memory
  - abseil/container/inlined_vector_internal (0.20200225.0):
    - abseil/base/core_headers
    - abseil/container/compressed_tuple
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/span
  - abseil/memory (0.20200225.0):
    - abseil/memory/memory (= 0.20200225.0)
  - abseil/memory/memory (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/meta (0.20200225.0):
    - abseil/meta/type_traits (= 0.20200225.0)
  - abseil/meta/type_traits (0.20200225.0):
    - abseil/base/config
  - abseil/numeric/int128 (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/strings/internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/meta/type_traits
  - abseil/strings/str_format (0.20200225.0):
    - abseil/strings/str_format_internal
  - abseil/strings/str_format_internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/types/span
  - abseil/strings/strings (0.20200225.0):
    - abseil/base/base
    - abseil/base/bits
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/base/throw_delegate
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/internal
  - abseil/time (0.20200225.0):
    - abseil/time/internal (= 0.20200225.0)
    - abseil/time/time (= 0.20200225.0)
  - abseil/time/internal (0.20200225.0):
    - abseil/time/internal/cctz (= 0.20200225.0)
  - abseil/time/internal/cctz (0.20200225.0):
    - abseil/time/internal/cctz/civil_time (= 0.20200225.0)
    - abseil/time/internal/cctz/time_zone (= 0.20200225.0)
  - abseil/time/internal/cctz/civil_time (0.20200225.0):
    - abseil/base/config
  - abseil/time/internal/cctz/time_zone (0.20200225.0):
    - abseil/base/config
    - abseil/time/internal/cctz/civil_time
  - abseil/time/time (0.20200225.0):
    - abseil/base/base
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/time/internal/cctz/civil_time
    - abseil/time/internal/cctz/time_zone
  - abseil/types (0.20200225.0):
    - abseil/types/any (= 0.20200225.0)
    - abseil/types/bad_any_cast (= 0.20200225.0)
    - abseil/types/bad_any_cast_impl (= 0.20200225.0)
    - abseil/types/bad_optional_access (= 0.20200225.0)
    - abseil/types/bad_variant_access (= 0.20200225.0)
    - abseil/types/compare (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - abseil/types/span (= 0.20200225.0)
    - abseil/types/variant (= 0.20200225.0)
  - abseil/types/any (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_any_cast
    - abseil/utility/utility
  - abseil/types/bad_any_cast (0.20200225.0):
    - abseil/base/config
    - abseil/types/bad_any_cast_impl
  - abseil/types/bad_any_cast_impl (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_optional_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_variant_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/compare (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/types/optional (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/bad_optional_access
    - abseil/utility/utility
  - abseil/types/span (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/meta/type_traits
  - abseil/types/variant (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_variant_access
    - abseil/utility/utility
  - abseil/utility/utility (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/meta/type_traits
  - AppAuth (1.4.0):
    - AppAuth/Core (= 1.4.0)
    - AppAuth/ExternalUserAgent (= 1.4.0)
  - AppAuth/Core (1.4.0)
  - AppAuth/ExternalUserAgent (1.4.0)
  - BoringSSL-GRPC (0.0.7):
    - BoringSSL-GRPC/Implementation (= 0.0.7)
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Implementation (0.0.7):
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Interface (0.0.7)
  - cloud_firestore (2.2.2):
    - Firebase/Firestore (= 8.0.0)
    - firebase_core
    - Flutter
  - cloud_functions (1.1.2):
    - Firebase/Functions (= 8.0.0)
    - firebase_core
    - Flutter
  - FBSDKCoreKit (9.3.0):
    - FBSDKCoreKit/Basics (= 9.3.0)
    - FBSDKCoreKit/Core (= 9.3.0)
  - FBSDKCoreKit/Basics (9.3.0)
  - FBSDKCoreKit/Core (9.3.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (9.3.0):
    - FBSDKLoginKit/Login (= 9.3.0)
  - FBSDKLoginKit/Login (9.3.0):
    - FBSDKCoreKit (~> 9.3.0)
  - Firebase/Auth (8.0.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 8.0.0)
  - Firebase/CoreOnly (8.0.0):
    - FirebaseCore (= 8.0.0)
  - Firebase/Firestore (8.0.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 8.0.0)
  - Firebase/Functions (8.0.0):
    - Firebase/CoreOnly
    - FirebaseFunctions (~> 8.0.0)
  - Firebase/Storage (8.0.0):
    - Firebase/CoreOnly
    - FirebaseStorage (~> 8.0.0)
  - firebase_auth (1.4.1):
    - Firebase/Auth (= 8.0.0)
    - firebase_core
    - Flutter
  - firebase_core (1.3.0):
    - Firebase/CoreOnly (= 8.0.0)
    - Flutter
  - firebase_storage (8.1.3):
    - Firebase/Storage (= 8.0.0)
    - firebase_core
    - Flutter
  - FirebaseAuth (8.0.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
    - GoogleUtilities/Environment (~> 7.4)
    - GTMSessionFetcher/Core (~> 1.5)
  - FirebaseCore (8.0.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.4)
    - GoogleUtilities/Logger (~> 7.4)
  - FirebaseCoreDiagnostics (8.1.0):
    - GoogleDataTransport (~> 9.0)
    - GoogleUtilities/Environment (~> 7.4)
    - GoogleUtilities/Logger (~> 7.4)
    - nanopb (~> 2.30908.0)
  - FirebaseFirestore (8.0.0):
    - abseil/algorithm (= 0.20200225.0)
    - abseil/base (= 0.20200225.0)
    - abseil/memory (= 0.20200225.0)
    - abseil/meta (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/time (= 0.20200225.0)
    - abseil/types (= 0.20200225.0)
    - FirebaseCore (~> 8.0)
    - "gRPC-C++ (~> 1.28.0)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 2.30908.0)
  - FirebaseFunctions (8.0.0):
    - FirebaseCore (~> 8.0)
    - GTMSessionFetcher/Core (~> 1.5)
  - FirebaseStorage (8.0.0):
    - FirebaseCore (~> 8.0)
    - GTMSessionFetcher/Core (~> 1.5)
  - Flutter (1.0.0)
  - flutter_login_facebook (0.5.0):
    - FBSDKLoginKit (~> 9.1)
    - Flutter
  - fluttertoast (0.0.2):
    - Flutter
    - Toast
  - google_sign_in (0.0.1):
    - Flutter
    - GoogleSignIn (~> 5.0)
  - GoogleDataTransport (9.0.1):
    - GoogleUtilities/Environment (~> 7.2)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (~> 1.2)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleUtilities/AppDelegateSwizzler (7.4.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.4.1):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.4.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (7.4.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.4.1)"
  - GoogleUtilities/Reachability (7.4.1):
    - GoogleUtilities/Logger
  - "gRPC-C++ (1.28.2)":
    - "gRPC-C++/Implementation (= 1.28.2)"
    - "gRPC-C++/Interface (= 1.28.2)"
  - "gRPC-C++/Implementation (1.28.2)":
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - "gRPC-C++/Interface (= 1.28.2)"
    - gRPC-Core (= 1.28.2)
  - "gRPC-C++/Interface (1.28.2)"
  - gRPC-Core (1.28.2):
    - gRPC-Core/Implementation (= 1.28.2)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Implementation (1.28.2):
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - BoringSSL-GRPC (= 0.0.7)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Interface (1.28.2)
  - GTMAppAuth (1.2.2):
    - AppAuth/Core (~> 1.4)
    - GTMSessionFetcher/Core (~> 1.5)
  - GTMSessionFetcher/Core (1.5.0)
  - leveldb-library (1.22.1)
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - package_info (0.0.1):
    - Flutter
  - PromisesObjC (1.2.12)
  - Toast (4.0.0)

DEPENDENCIES:
  - cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)
  - cloud_functions (from `.symlinks/plugins/cloud_functions/ios`)
  - FBSDKCoreKit
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_storage (from `.symlinks/plugins/firebase_storage/ios`)
  - Flutter (from `Flutter`)
  - flutter_login_facebook (from `.symlinks/plugins/flutter_login_facebook/ios`)
  - fluttertoast (from `.symlinks/plugins/fluttertoast/ios`)
  - google_sign_in (from `.symlinks/plugins/google_sign_in/ios`)
  - package_info (from `.symlinks/plugins/package_info/ios`)

SPEC REPOS:
  trunk:
    - abseil
    - AppAuth
    - BoringSSL-GRPC
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseFirestore
    - FirebaseFunctions
    - FirebaseStorage
    - GoogleDataTransport
    - GoogleSignIn
    - GoogleUtilities
    - "gRPC-C++"
    - gRPC-Core
    - GTMAppAuth
    - GTMSessionFetcher
    - leveldb-library
    - nanopb
    - PromisesObjC
    - Toast

EXTERNAL SOURCES:
  cloud_firestore:
    :path: ".symlinks/plugins/cloud_firestore/ios"
  cloud_functions:
    :path: ".symlinks/plugins/cloud_functions/ios"
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_storage:
    :path: ".symlinks/plugins/firebase_storage/ios"
  Flutter:
    :path: Flutter
  flutter_login_facebook:
    :path: ".symlinks/plugins/flutter_login_facebook/ios"
  fluttertoast:
    :path: ".symlinks/plugins/fluttertoast/ios"
  google_sign_in:
    :path: ".symlinks/plugins/google_sign_in/ios"
  package_info:
    :path: ".symlinks/plugins/package_info/ios"

SPEC CHECKSUMS:
  abseil: 6c8eb7892aefa08d929b39f9bb108e5367e3228f
  AppAuth: 31bcec809a638d7bd2f86ea8a52bd45f6e81e7c7
  BoringSSL-GRPC: 8edf627ee524575e2f8d19d56f068b448eea3879
  cloud_firestore: 83d6cd19d24798c523265494ab81db32009fcb7b
  cloud_functions: 76c1a4e38a1b11e657a10d2edbcc214869e52003
  FBSDKCoreKit: 0d1ae58388a458b8222f72025804cdc84eb5d0c3
  FBSDKLoginKit: aea68df6121c5e165ccae2fabfdc83c4644ee40f
  Firebase: 73c3e3b216ec1ecbc54d2ffdd4670c65c749edb1
  firebase_auth: 6532658f5a4f76be32cd5e7518753ebedd4544d2
  firebase_core: cda81ae37eda6df2bc2d16027fda527987c4bd33
  firebase_storage: 1c82ef47319a51b82b216475b91a102bca2e66d0
  FirebaseAuth: b8cd992fca5b53dc6eec09e873a3f375f000c5a1
  FirebaseCore: 3f09591d51292843e2a46f18358d60bf4e996255
  FirebaseCoreDiagnostics: 3e249cee3de5c5f9cfd6cc2a19997231286fec11
  FirebaseFirestore: 7f6576eaca9f821e864c3e917d68aa99f4e6b613
  FirebaseFunctions: 57fedef9b8808b83be40e176bcb28aa2aa78cf92
  FirebaseStorage: 61bcd27880fa17362f68be67d3683d04bfd7b1c7
  Flutter: 434fef37c0980e73bb6479ef766c45957d4b510c
  flutter_login_facebook: 41fcf15687d2ce7a75bb89aa3476df54a00845a3
  fluttertoast: 6122fa75143e992b1d3470f61000f591a798cc58
  google_sign_in: 6bd214b9c154f881422f5fe27b66aaa7bbd580cc
  GoogleDataTransport: 04c3e9a480bbcaa2ec3f5d27f1cdeb6a92f20c8d
  GoogleSignIn: 7137d297ddc022a7e0aa4619c86d72c909fa7213
  GoogleUtilities: f8a43108b38a68eebe8b3540e1f4f2d28843ce20
  "gRPC-C++": 13d8ccef97d5c3c441b7e3c529ef28ebee86fad2
  gRPC-Core: 4afa11bfbedf7cdecd04de535a9e046893404ed5
  GTMAppAuth: ad5c2b70b9a8689e1a04033c9369c4915bfcbe89
  GTMSessionFetcher: b3503b20a988c4e20cc189aa798fd18220133f52
  leveldb-library: 50c7b45cbd7bf543c81a468fe557a16ae3db8729
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  package_info: 873975fc26034f0b863a300ad47e7f1ac6c7ec62
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
  Toast: 91b396c56ee72a5790816f40d3a94dd357abc196

PODFILE CHECKSUM: 425d381e9b612d5c321c25c91b0d3f3541b2b237

COCOAPODS: 1.10.1
`

**Comment by greymag** [comment]
Thanks for the additional info! Podfile looks OK. I just did compile an example app with exactly this versions of the dependencies. Did you try to run `flutter clean`? "Build -> Clean" in Xcode? 

If you are and it doesn't help, can you please try to compile current version of example app from this repo and tell me if it works or not.

**Comment by dmvvilela** [comment]
Strange.. the example app actually compiled. I did flutter clean and also tried build -> clean on x-code

**Comment by dmvvilela** [comment]
I created another project and everything worked fine. It must be some config problem, mas project was very old (before flutter 1.0)
