### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by ravdeepsingh22** [Innim/flutter_login_facebook#53]
By adding flutter_login_facebook: ^1.0.1 , the following dependencies stop working and throw a similar error 

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

Effected dependencies
path_provider: ^2.0.2
sqflite
moor_flutter: ^4.0.0

**Comment by greymag** [comment]
Hey! Most likely you didn't set up your application correctly. Check out [README](https://github.com/Innim/flutter_login_facebook#edit-your-resources-and-manifest).

Also see #45 

Please let me know if that helps or not.

**Comment by greymag** [comment]
No feedback, so I'm closing it.
