### ISSUE TITLE
Unhandled Exception: 'package:flutter_login_facebook/src/facebook_login.dart'

### ISSUE THREAD

**Issue by keshavbhusal1** [Innim/flutter_login_facebook#58]
Unhandled Exception: 'package:flutter_login_facebook/src/facebook_login.dart': Failed assertion: line 163 pos 12: 'Platform.isAndroid': is not true.

This is issue found in IOS Device(Iphone)

**Comment by greymag** [comment]
Hey!
You can't use `expressLogin` on iOS, it's Android option. See method's [documentation](https://github.com/Innim/flutter_login_facebook/blob/e9194ba65516bc90405c0a48f3116cfa680f5ac8/lib/src/facebook_login.dart#L156)

**Comment by keshavbhusal1** [comment]
Thank you @graymag

**Comment by keshavbhusal1** [comment]
Thank you @greymag
