### ISSUE TITLE
Use of deprecated API - Android

### ISSUE THREAD

**Issue by tomassasovsky** [Innim/flutter_login_facebook#59]
Note: C:\Users\Tomas\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_login_facebook-1.2.0\android\src\main\java\ru\innim\flutter_login_facebook\FlutterLoginFacebookPlugin.java uses or overrides a deprecated API.

**Comment by greymag** [comment]
Removed in [1.4.0](https://pub.dev/packages/flutter_login_facebook/versions/1.4.0)
