### ISSUE TITLE
Starting with v13 of the SDK

### ISSUE THREAD

**Issue by keshavbhusal1** [Innim/flutter_login_facebook#60]
Starting with v13 of the SDK, a client token must be embedded in your client code before making Graph API calls. Visit https://developers.facebook.com/docs/android/getting-started#client-token to learn how to implement this change.

Why every time show this warning.

**Comment by greymag** [comment]
Hey!

This is just an information, that intended to force developers migrate their application beforehand:

> Beginning with SDK v13.0, set to release in early 2022, a Client Token will be required for all calls to the Graph API.

You can add Client Token as described in [documentation](https://developers.facebook.com/docs/android/getting-started#app_id).

I will update package readme soon.
