### ISSUE TITLE
invalid result on get email

### ISSUE THREAD

**Issue by keshavbhusal1** [Innim/flutter_login_facebook#61]
My ios App get this error
Get user email error: PlatformException(UNKNOWN, Invalid result on get email: (Function), null, null)

    var login = await facebookLogin.logIn(permissions: [
      FacebookPermission.publicProfile,
      FacebookPermission.email,
    ]);

    if (Platform.isAndroid) {
      login = await facebookLogin.expressLogin();
    }
    switch (login.status) {
      case FacebookLoginStatus.success:

     await facebookLogin.getUserProfile();
        final token = await facebookLogin.accessToken;
        debugPrint("token $token");
        if(token!.permissions.contains(FacebookPermission.email.name)){
        final _email = await facebookLogin.getUserEmail();
        debugPrint("email $_email");

        }

        break;
      case FacebookLoginStatus.cancel:
        ToastHelper.showShort("Login cancelled by the user.");

        break;
      case FacebookLoginStatus.error:
        ToastHelper.showErrorLong(
            'Something went wrong with the login process.\n'
            'Here\'s the error Facebook gave us: ${login.error}');

        break;
    
  }

**Comment by greymag** [comment]
Hey! Sorry for the late reply, somehow I missed this issue. Is the problem still relevant?

**Comment by greymag** [comment]
Closed due to inactivity. If the problem is still relevant, fill free to reopen it.
