### ISSUE TITLE
No method to get uploaded or tagged photos of the user when logged in successfully

### ISSUE THREAD

**Issue by grover702** [Innim/flutter_login_facebook#65]

**Comment by greymag** [comment]
Hey!

The plugin purpose is just log in with Facebook account and get some basic information for displaying in the app. 

If you want do something more complex you should do it yourself. You can implement methods for making requests to the GraphAPI as an [extension method](https://dart.dev/guides/language/extension-methods) or just making graph api request with http or dio as I suggest [here](https://github.com/Innim/flutter_login_facebook/issues/13#issuecomment-655598424).
