### ISSUE TITLE
How to get phone number if user was logged in with phone number ?

### ISSUE THREAD

**Issue by phantom1511** [Innim/flutter_login_facebook#71]
I have a question how do i get phone number if user was logged in with phone number, i need it to send in to server cause there are some situations when user logged in with phone number and and i can't send data cause there is null

**Comment by greymag** [comment]
Hey! As far as I know - you can't. Facebook had this permission in past, but removed it.

**Comment by phantom1511** [comment]
@greymag

**Comment by greymag** [comment]
I understood what you said, the answer still - you can't =) 

When user logged with Facebook account in your app, all you have for authentication is token from FB. Any other information: email, name, phone - it's just additional profile information. Some you can get, some you can not. If you require user's email/phone in your app and Facebook doesn't provide it, you should request if from user in your app UI.

Again, I'm not 100% sure, you can looking for yourself.
