### ISSUE TITLE
Update Android / IOS fB SDK to 13

### ISSUE THREAD

**Issue by sanket2798** [Innim/flutter_login_facebook#73]
can you pls update the FB SDK version to 13

**Comment by sanket2798** [comment]
@greymag hey!! any update on this??

**Comment by greymag** [comment]
Hey! Sorry, I was pretty busy. I will try do it in the near future

**Comment by sanket2798** [comment]
@greymag pls can you do this ASAP because we use this plugin in our project and FB continuously send email to us...

**Comment by greymag** [comment]
[v1.5.0](https://pub.dev/packages/flutter_login_facebook/versions/1.5.0)
