### ISSUE TITLE
Changing the text modal permission to open facebook

### ISSUE THREAD

**Issue by ririlya94** [Innim/flutter_login_facebook#75]
Hi,

Does anyone know to change the text "Runner" to the app name instead? Without changing the project name

![image](https://user-images.githubusercontent.com/11284989/170401859-064d3965-c15b-4bcd-b862-19deaa60b214.png)

**Comment by greymag** [comment]
Hey! You need to change app name in in Info.plist https://greymag.medium.com/flutter-how-to-change-app-name-on-ios-291f510cb058
