### ISSUE TITLE
Getting accessToken never returns in latest update causing some bad issues

### ISSUE THREAD

**Issue by PerLycke** [Innim/flutter_login_facebook#76]
https://github.com/Innim/flutter_login_facebook/blob/3314600fd3da6643a3070f4aa2aada75a9ed58ef/lib/src/facebook_login.dart#L34

The linked function never returns after updating to plugin version 1.5.0 causing severe issues (e.g. you won't get a result from isLoggedIn).

I see your code changes just imply updating the underlying FB SDK. Did they make changes in the SDK you need to update accordingly to?

**Comment by greymag** [comment]
Hey! On which platform?

**Comment by PerLycke** [comment]
Oops, sorry should've included that info. I found the issue using a Samsung, Android 12 and my doctor output is the following:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] VS Code (version 1.67.2)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability
> 
> • No issues found!

**Comment by greymag** [comment]
Just checked - all working well. 

Do you made previous [migration](https://github.com/Innim/flutter_login_facebook/blob/master/UPGRADE.md#android)? 
Is there any errors in logcat?

**Comment by PerLycke** [comment]
That's it. Missed the most recent migration 👍
