### ISSUE TITLE
Error is coming after pod update

### ISSUE THREAD

**Issue by GaoWhitebird** [Innim/flutter_login_facebook#78]
Swift Compiler Error (Xcode): Cannot find type 'Permission' in scope
/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:192:70

Swift Compiler Error (Xcode): Cannot find 'Permission' in scope
/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:49:57

Swift Compiler Error (Xcode): Extra trailing closure passed in call
/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:198:10

Swift Compiler Error (Xcode): Value of type 'AccessToken' has no member 'permissions'
/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:243:33

Swift Compiler Error (Xcode): Value of type 'AccessToken' has no member 'declinedPermissions'
/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:244:41

Encountered error while building for device.

**Comment by greymag** [comment]
Hey. Which Xcode version do you use?

**Comment by GaoWhitebird** [comment]
XCode version is 13.4

**Comment by greymag** [comment]
Try:
- `flutter clean`
- open `/ios` in Xcode and select Product -> Clean build folder

If this doesn't fix a problem - try to delete `example/ios/Podfile.lock` and run app again.

Please let me know if any of this helps.

**Comment by GaoWhitebird** [comment]
I have tried several times but result is the same.
Just try this and it is working.
I removed ^ and reimport.

flutter_login_facebook:  1.4.1

in pubspec.yaml file.

**Comment by greymag** [comment]
So previous version working, but last one doesn't. That's very odd, I checked it before release. Let me check again and I'll come back to you.

**Comment by daltoncabrera** [comment]
> Swift Compiler Error (Xcode): Cannot find type 'Permission' in scope /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:192:70
> 
> Swift Compiler Error (Xcode): Cannot find 'Permission' in scope /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:49:57
> 
> Swift Compiler Error (Xcode): Extra trailing closure passed in call /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:198:10
> 
> Swift Compiler Error (Xcode): Value of type 'AccessToken' has no member 'permissions' /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:243:33
> 
> Swift Compiler Error (Xcode): Value of type 'AccessToken' has no member 'declinedPermissions' /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:244:41
> 
> Encountered error while building for device.

Hello guys, I'm facing same issue, with XCode 13.4 on mac mini M1.

Regards.

**Comment by GaoWhitebird** [comment]
@daltoncabrera 

you can try this.

flutter_login_facebook: 1.4.1

without ^

**Comment by daltoncabrera** [comment]
> @daltoncabrera
> 
> you can try this.
> 
> flutter_login_facebook: 1.4.1
> 
> without ^

Thank you @GaoWhitebird , that made the trick.

**Comment by greymag** [comment]
@daltoncabrera this doesn't fix the problems - you just use an old version.

I just checked again with a latest version on a clean project - all works fine.

@daltoncabrera @GaoWhitebird do you have Swift as a default language in your project? (you can check AppDelegate)

**Comment by fleoparra** [comment]
Same problem here. I use Mac M1 with XCode 13.4.1

> /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:193:71: error: cannot find type 'Permission' in scope
>         private func logIn(result: @escaping FlutterResult, permissions: [Permission]) {
>                                                                           ^~~~~~~~~~
> /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:50:58: error: cannot find 'Permission' in scope
>                 let permissions = permissionsArg.map {val in Permission(stringLiteral: val)}
>                                                              ^~~~~~~~~~
> /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:199:11: error: extra trailing closure passed in call
>             ) { res in
>               ^~~~~~~~
> /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:244:34: error: value of type 'AccessToken' has no member 'permissions'
>                 "permissions": token.permissions.map {item in item.name},
>                                ~~~~~ ^~~~~~~~~~~
> /.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:245:42: error: value of type 'AccessToken' has no member 'declinedPermissions'
>                 "declinedPermissions": token.declinedPermissions.map {item in item.name},
>                                        ~~~~~ ^~~~~~~~~~~~~~~~~~~
>     Command CompileSwiftSources failed with a nonzero exit code

Version 1.4.1 works fine.

**Comment by greymag** [comment]
@fleoparra do you have Swift as a default language in your project? (you can check AppDelegate)

**Comment by fleoparra** [comment]
@greymag Yes, my AppDelegate is in swift. In my case for a while my project works on debug without problems with the new version but when I try to build for release: `flutter build ios --release` the project show me the error.

**Comment by expertdev-designer** [comment]
Any Solution for the issue, I have the same issue unable to build for iOS. Any Update

**Comment by greymag** [comment]
@expertdev-designer please downgrade to 1.4 for now, I'm still trying to resolve it

**Comment by kapilmobikul** [comment]
@greymag any update on this issue?
 still facing this issue while building iPA
 
Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:193:71: Cannot find type 'Permission' in scope

**Comment by GaoWhitebird** [comment]
@expertdev-designer 

you can try this.

flutter_login_facebook: 1.4.1

without ^

**Comment by kapilmobikul** [comment]
@expertdev-designer 
tried your given solution 
flutter_login_facebook: 1.4.1

but still same issue

**Comment by nicolobozzato** [comment]
@kapilmobikul you downgrade the version but if it gives you still this error
`Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_login_facebook-1.5.0/ios/Classes/SwiftFlutterLoginFacebookPlugin.swift:193:71: Cannot find type 'Permission' in scope`

related to version 1.5.0 it probably means that your project didn't receipt the update of version, clean do a flutter clean, clean the cache, delete pod folder and Podfile.lock, and "cd ios && pod install" again

**Comment by greymag** [comment]
@fleoparra @daltoncabrera @expertdev-designer @GaoWhitebird Just published [1.5.0+1](https://pub.dev/packages/flutter_login_facebook/versions/1.5.0+1). Please, check if the issue was fixed or not

**Comment by GaoWhitebird** [comment]
It is working now. Thanks. I will close this.
