### ISSUE TITLE
Infinite loop for IOS user with native Facebook app and not logged on Safari

### ISSUE THREAD

**Issue by nicolobozzato** [Innim/flutter_login_facebook#80]
Many users have this problem: they remain stuck in an infinite loop between webview and the request to log in with their Facebook app.
This happened usually if they are not logged in on Safari.

My guess is that this refers to the 5th paragraph of the IOS implementation instruction

https://developers.facebook.com/docs/facebook-login/ios?locale=en_US

> This code initializes the SDK when your app launches, and allows the SDK to handle logins and sharing from the native Facebook app when you perform a Login or Share action. Otherwise, the user must be logged into Facebook to use the in-app browser to log in.

Especially I think it could be the part linked to the SceneDelegate not present maybe?

Thanks

**Comment by greymag** [comment]
Hey. Do you have `SceneDelegate` in your app?

**Comment by nicolobozzato** [comment]
Hi! Thank you for the answer, no in my app I don't have a SceneDelegate. Sorry if my guess doesn't make sense. What do you think could be the problem?

**Comment by nicolobozzato** [comment]
I found the solution. The problem was the implementation of the package 
flutter-braintree
that has this issue 
https://github.com/pikaju/flutter-braintree/issues/122

Thanks for the attention,the bug can be closed
