### ISSUE TITLE
Login not work in IOS

### ISSUE THREAD

**Issue by giovannilima262** [Innim/flutter_login_facebook#83]
`
     ...
     fbLoginResult ??= await _facebookLogin.logIn(
        permissions: [FacebookPermission.email],
      );
      ...
`

**Current state:** When calling the login function facebook, the modal opens normally and when going through the authentication screens I am redirected to the first facebook screen and nothing else happens.

**Expected state:** After the last authentication confirmation option, be returned to the app with a successful authentication.

**Obs:** The problem happens for versions older than 1.5.0+1 and It works if I don't use the app

Plugin version: 1.5.0+1
XCode version: 13.4.1
Device: iPhone 11 (iOS 15.5)

**Comment by greymag** [comment]
Hey.

Can you, please, upload a video?

**Comment by giovannilima262** [comment]
When clicking on the blue button it stays in a loop and returns to the same screen

https://user-images.githubusercontent.com/22526617/177830797-52e5e383-ceaf-4a30-ba52-b7f35e2afcf1.mov

**Comment by mero-jung** [comment]
same here..

**Comment by greymag** [comment]
That's not good at all =) I'll take a look. You can downgrade to 1.4 version for now

**Comment by greymag** [comment]
Hm, I can't reproduce it, all works fine:

https://user-images.githubusercontent.com/1502131/178295922-e4ef46d8-4461-4a40-b1a4-2f757913765f.MP4

@giovannilima262 Can you provide a minimal example of project that don't works?

**Comment by giovannilima262** [comment]
https://github.com/darwin-morocho/flutter-facebook-auth/issues/263#issuecomment-1180779334

**Comment by giovannilima262** [comment]
[solution](https://github.com/darwin-morocho/flutter-facebook-auth/issues/263#issuecomment-1180779334)
