### ISSUE TITLE
Failed to list versions for com.facebook.android:facebook-login

### ISSUE THREAD

**Issue by rlaheri99** [Innim/flutter_login_facebook#89]
My project was working fine till tomorrow now I'm getting this error in my all projects which have `facebookLogin`.

- **pubspac.yaml**

    flutter_login_facebook: ^1.6.0

- **compileSdkVersion**

        compileSdkVersion 33

- **minSdkVersion**

    

       minSdkVersion 20

- **repositories** 
 
       repositories {
                google()
                mavenCentral()
            }

- **dependencies** 
  

      dependencies {
            implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
            implementation platform('com.google.firebase:firebase-bom:29.2.1')
            implementation 'com.google.firebase:firebase-analytics-ktx'
            implementation 'com.facebook.android:facebook-login:latest.release'
        }

I'm facing the below error.

    * What went wrong:
    Execution failed for task ':app:checkDebugAarMetadata'.
    > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
       > Could not resolve com.facebook.android:facebook-login:latest.release.
         Required by:
             project :app
          > Failed to list versions for com.facebook.android:facebook-login.
             > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-login/maven-metadata.xml.
                > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-login/maven-metadata.xml'.
                   > Read timed out

**Comment by savadmv** [comment]
Same situation here. Correcting the mistake.Replacing 'Tomorrow ' with 'Yesterday'

**Comment by rlaheri99** [comment]
Thank you for the timely update it works like a charm.
