### ISSUE TITLE
Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared

### ISSUE THREAD

**Issue by tomyamGTX** [Innim/flutter_login_facebook#93]
W/com.facebook.internal.NativeProtocol( 7825): Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.

My android Manifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.aqwise.tamadun_documentary.tamadun_documentary">

    <queries>
        <provider android:authorities="com.facebook.katana.provider.PlatformProvider" /> 
        <provider android:authorities="com.facebook.orca.provider.PlatformProvider" /> 
    </queries>

    <uses-permission android:name="android.permission.INTERNET"/>

    <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>

    <application
        android:label="Tamadun Kuno"
        android:name="${applicationName}"
        android:exported="true"
        android:usesCleartextTraffic="true"
        android:icon="@mipmap/ic_launcher"
        tools:targetApi="m">
       <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
       <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by ehmiii** [comment]
Did you fixed it?

**Comment by TopsyCretts** [comment]
Had the same issue, so check: had you install and open Facebook app on device.
