### ISSUE TITLE
How to validate access token on server?

### ISSUE THREAD

**Issue by lukehutch** [Innim/flutter_login_facebook#96]
The docs suggest:

```dart
    // Send access token to server for validation and auth
    final FacebookAccessToken accessToken = res.accessToken;
```

however there is no example shown of how the access token can be validated on the app developer's own server, to ensure that the user did actually successfully log in via Facebook OAuth2. If the app server doesn't validate the token, then the user can just give some random token to the app server, and say "this is my Facebook access token", and the sever will accept the fake login.

Please update the docs to show how this is supposed to be done.

**Comment by greymag** [comment]
Hey!

This moment is a little messy and unclear in the Facebook documentation, so I can't provide you a 100% valid guide on how to do that.

However I can offer an option on how to do that.

You will need to use an endpoint with the disturbing name `debug_token` ([documentation](https://developers.facebook.com/docs/facebook-login/guides/%20access-tokens/debugging)):

```
https://graph.facebook.com/debug_token?
  input_token={input-token}&
  access_token={valid-access-token}
```

With this endpoint you can check the access token from the client (`input_token`) and get some info (including `user_id`).

But first you need to get an access token for server calls (`access_token`). You can do it with `oauth/access_token` ([documentation](https://developers.facebook.com/docs/facebook-login/guides/access-tokens#apptokens)):

```
https://graph.facebook.com/oauth/access_token
  ?client_id={your-app-id}
  &client_secret={your-app-secret}
  &grant_type=client_credentials
```

You can read this [article](https://medium.com/@byn9826/verify-facebook-login-by-python-e02ac1e23e37) for a more detailed explanation.

**Comment by lukehutch** [comment]
Thanks for the fast response!

The `your-app-id` and `your-app-secret` values are saved in the manifest file in Android and the Info.plist file on iOS. I assume there's no uniform way for the Dart code on the client to pull these out of the appropriate platform code, depending on the mobile platform, so that it can pass these encrypted to the server? I want to avoid having to put the same exact values in a third place, in order for the server to have access to them.

**Comment by greymag** [comment]
No, `your-app-secret` should **never** be on the client side. Both parameters should be defined on the server side, in the configuration (well, you can pass `app-id` from the client, but this is less secure and there is no point in that).

**Comment by lukehutch** [comment]
Ah, OK, I was confusing `your-app-secret` with `facebook_client_token` on the client. Thanks for clarifying. I'll try to implement this.

**Comment by lukehutch** [comment]
(Although I just realized that `flutter_login_facebook` does not yet support Web, so I may not be able to use your library yet, even though your code looks like a higher-quality implementation than `flutter_facebook_auth`...)
