### ISSUE TITLE
[!] Error installing FBSDKCoreKit

### ISSUE THREAD

**Issue by pen110** [Innim/flutter_login_facebook#97]
I use this version [flutter_login_facebook: ^1.8.0]
but can't use it. 

[!] Error installing FBSDKCoreKit
[!] /usr/bin/curl -f -L -o /var/folders/jb/ww1h6xsd37s95z8y7jgbs6_80000gn/T/d20230411-12197-enbjh/file.zip https://github.com/facebook/facebook-ios-sdk/releases/download/v16.0.1/FacebookSDK_Dynamic.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:50 --:--:--     0
curl: (56) LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60

**Comment by greymag** [comment]
Hello! It's "Operation timed out" error. Check your Internet connection and try again. Please, write in comments about the result.

**Comment by pen110** [comment]
I dont think so,&nbsp;Tried many times, but finally was. with 4G , wifi ,both error




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Innim/flutter_login_facebook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Innim/flutter_login_facebook] [!] Error installing FBSDKCoreKit (Issue #97)





 
Hello! It's "Operation timed out" error. Check your Internet connection and try again. Please, write in comments about the result.

**Comment by greymag** [comment]
Try 
```
/usr/bin/curl -f -L -o ./file.zip https://github.com/facebook/facebook-ios-sdk/releases/download/v16.0.1/FacebookSDK_Dynamic.xcframework.zip
```
in Terminal. Does it work?

**Comment by pen110** [comment]
THANKS, it's working!!
